[env:esp32dev_full]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_src_filter = +<main_temp_turb.cpp>

lib_deps =
  https://github.com/mobizt/Firebase-ESP-Client.git#v4.4.17
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  https://github.com/esphome/ESPAsyncWebServer.git
  https://github.com/esphome/AsyncTCP.git

[env:esp32dev_servo]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_src_filter = +<main_servo.cpp>
lib_archive = yes

lib_deps =
  https://github.com/mobizt/Firebase-ESP-Client.git#v4.4.17
  paulstoffregen/OneWire
  milesburton/DallasTemperature

[env:esp32dev_aerator]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_aerator.cpp>

[env:esp32dev_servo_relay]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = -DUSE_REAL_FIREBASE
build_src_filter = +<main_servo_relay.cpp> +<servo_ctrl.cpp> +<common.cpp>

lib_deps =
  https://github.com/mobizt/Firebase-ESP-Client.git#v4.4.17
  paulstoffregen/OneWire
  milesburton/DallasTemperature

[env:esp32dev_sensor]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = -DUSE_REAL_FIREBASE
build_src_filter = +<main_sensor.cpp> +<turbidity.cpp> +<common.cpp>

lib_deps =
  https://github.com/mobizt/Firebase-ESP-Client.git#v4.4.17
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  marcoschwartz/LiquidCrystal_I2C

[env:esp32dev_combined]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_src_filter = +<main_combined.cpp> +<turbidity.cpp> +<servo_ctrl.cpp> +<common.cpp>

lib_deps =
  https://github.com/mobizt/Firebase-ESP-Client.git#v4.4.17
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  https://github.com/esphome/ESPAsyncWebServer.git
  https://github.com/esphome/AsyncTCP.git

[env:esp32dev_allinone]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = -DUSE_REAL_FIREBASE
build_src_filter = +<main_allinone.cpp> +<servo_ctrl.cpp> +<turbidity.cpp> +<ph_ctrl.cpp> +<do_ctrl.cpp> +<common.cpp>

lib_deps =
  https://github.com/mobizt/Firebase-ESP-Client.git#v4.4.17
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  marcoschwartz/LiquidCrystal_I2C

[env:esp32dev_do_local]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_src_filter = +<main_do_lcd_local.cpp> +<do_ctrl.cpp>
lib_deps =
  marcoschwartz/LiquidCrystal_I2C
