[env:esp32dev_full]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_src_filter = +<main_temp_turb.cpp>

lib_deps =
  https://github.com/mobizt/Firebase-ESP-Client.git#v4.4.17
  https://github.com/esphome/ESPAsyncWebServer.git
  https://github.com/esphome/AsyncTCP.git
  paulstoffregen/OneWire
  milesburton/DallasTemperature

[env:esp32dev_servo]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_src_filter = +<*> -<main.cpp>
lib_archive = yes

lib_deps =
  https://github.com/mobizt/Firebase-ESP-Client.git#v4.4.17