// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjDOkzE4iubiLx_xA2YufMUMo6jgIKcaw',
    appId: '1:937626111574:web:b017b7d712a778f1ebf5f7',
    messagingSenderId: '937626111574',
    projectId: 'craycare-8436c',
    authDomain: 'craycare-8436c.firebaseapp.com',
    databaseURL: 'https://craycare-8436c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'craycare-8436c.firebasestorage.app',
    measurementId: 'G-4V8D7D1GMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIidS1Y6wysetztz1pSSIWlHTcaQFeAE4',
    appId: '1:937626111574:android:5376b3897ae7d28eebf5f7',
    messagingSenderId: '937626111574',
    projectId: 'craycare-8436c',
    databaseURL: 'https://craycare-8436c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'craycare-8436c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOEPPoAGp6XG5ErjRpj-r9iqGCb1bNpUE',
    appId: '1:937626111574:ios:e5532f7292d4ccaaebf5f7',
    messagingSenderId: '937626111574',
    projectId: 'craycare-8436c',
    databaseURL: 'https://craycare-8436c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'craycare-8436c.firebasestorage.app',
    iosClientId: '937626111574-mt95q0fnik4o3su9gj0absindg08pieg.apps.googleusercontent.com',
    iosBundleId: 'com.example.craycare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOEPPoAGp6XG5ErjRpj-r9iqGCb1bNpUE',
    appId: '1:937626111574:ios:e5532f7292d4ccaaebf5f7',
    messagingSenderId: '937626111574',
    projectId: 'craycare-8436c',
    databaseURL: 'https://craycare-8436c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'craycare-8436c.firebasestorage.app',
    iosClientId: '937626111574-mt95q0fnik4o3su9gj0absindg08pieg.apps.googleusercontent.com',
    iosBundleId: 'com.example.craycare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjDOkzE4iubiLx_xA2YufMUMo6jgIKcaw',
    appId: '1:937626111574:web:8c7faafc8dace1aeebf5f7',
    messagingSenderId: '937626111574',
    projectId: 'craycare-8436c',
    authDomain: 'craycare-8436c.firebaseapp.com',
    databaseURL: 'https://craycare-8436c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'craycare-8436c.firebasestorage.app',
    measurementId: 'G-N657M6N33X',
  );
}
